name: Cache Node and NPM Dependencies
description: Cache Node.js and NPM dependencies based on package-lock.json

inputs:
  node-version:
    description: NodeJS version to use
    required: true
    default: 20.x

  working-dir:
    description: The working directory of the application
    required: false
    default: .

  target-env:
    description: dev or prod. Controls whether dev dependencies are installed
    required: false
    default: dev

runs:
  using: composite
  steps:
    - name: Setup NodeJS ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ${{ inputs.working-dir }}/node_modules
        key: node-modules-${{ inputs.target-env }}-${{ hashFiles(format('{0}/package-lock.json', inputs.working-dir)) }}

    - name: Install dependencies
      shell: bash
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      working-directory: ${{ inputs.working-dir }}
      run: |
        if [ "${{ inputs.target-env }}" = "dev" ]; then
          npm ci
        else
          npm ci --omit=dev
        fi
